### ISSUE TITLE
How to run state-based notebook with pred_horizon which is not a power of 2?

### ISSUE THREAD

**Issue by qureshinomaan** [columbia-ai-robotics/diffusion_policy#3]
Hi, 
Thanks a lot for making the code very easy to interpret and set up! 
I have been playing around with the policy, and it seems like currently, it is not able to handle "pred_horizon" which is not a power of 2. For example, it works for pred_horizon = 2, 4, 8, 16 .... but doesn't work for other values. Is there a quick solution to this?

**Comment by cheng-chi** [comment]
Since the Diffusion Policy in notebooks are implemented with CNN(i.e. UNet)-based backbones, the accepted prediction horizon is limiated by UNet's up/down resolution operations. [Transformer based Diffuison Policy](https://github.com/columbia-ai-robotics/diffusion_policy/blob/main/diffusion_policy/policy/diffusion_transformer_lowdim_policy.py) in our main repo should be able to accept any prediction horizon.
